# Generated by Django 3.1.5 on 2021-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('career', models.TextField()),
                ('alt_career', models.TextField()),
                ('jobs', models.TextField()),
            ],
        ),
    ]
