# Generated by Django 3.1.7 on 2021-03-01 11:24

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='alt_career',
        ),
        migrations.RemoveField(
            model_name='course',
            name='career',
        ),
        migrations.RemoveField(
            model_name='course',
            name='jobs',
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default=1000, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
