# Generated by Django 3.1.7 on 2021-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.TextField(default='subtitle'),
            preserve_default=False,
        ),
    ]
