# Generated by Django 3.1.7 on 2021-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='service/bg'),
        ),
    ]
