# Generated by Django 3.1.7 on 2021-03-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
