# Generated by Django 3.1.7 on 2021-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='designation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
